version: '3'
volumes:
  empty:
services:
  http:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./http/hngex.email.conf:/etc/nginx/conf.d/hngex.email.conf
      - ./http/html:/var/www/html
      - ./certs/letsencrypt:/etc/letsencrypt
      - /etc/localtime:/etc/localtime:ro
  cert:
    image: certbot/certbot:latest
    volumes:
      - ./http/html:/html
      - ./certs/letsencrypt:/etc/letsencrypt
  imap:
    hostname: imap
    build: ./imap
      #ports:
      #  - "24"
      #  - "2525"
      #  - "993:993"
    volumes:
      - ./data/mail:/mail
      - ./imap/users:/etc/dovecot/users
      - ./imap/dovecot.conf:/etc/dovecot/dovecot.conf
      - ./certs/letsencrypt:/etc/letsencrypt
      - /etc/localtime:/etc/localtime:ro
    restart: always
    network_mode: "host"
  smtp:
    hostname: smtp
    build: ./smtp
      #ports:
      #  - "25:25"
      #  - "587:587"
    volumes:
      - ./data/queue:/var/spool/postfix
      - empty:/var/spool/postfix/etc
      - ./smtp/vmailbox:/etc/postfix/vmailbox
      - ./smtp/main.cf:/etc/postfix/main.cf
      - ./smtp/master.cf:/etc/postfix/master.cf
      - ./certs/letsencrypt:/etc/letsencrypt
      - /etc/localtime:/etc/localtime:ro
    restart: always
    depends_on:
      - imap
    network_mode: "host"
  smtp-proxy:
    hostname: smtp-proxy
    build: ./smtp-proxy
    command: /sbin/warp -ip 0.0.0.0 -port 10025
      #ports:
      #  - "10025"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../warp/warp:/sbin/warp
        #cap_add:
        #  - NET_ADMIN
        #  - SYS_PTRACE
    privileged: true
    network_mode: "host"
    restart: always
